run:
  timeout: 15m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs:
    - helm
    - hack
    - terraform
    - tessel8/hack

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-tags:
      - experimental
    settings:
      hugeParam:
        sizeThreshold: 1024 # in bytes (default is 80)
  gocyclo:
    min-complexity: 20
  errcheck:
    exclude: ./errcheck_excludes.txt
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  testpackage:
    skip-regexp: (export|internal|)_test\.go
  nolintlint:
    allow-unused: true
    require-specific: false
    require-explanation: true
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - funlen
    - gas
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unused
    - whitespace

    # - lll # disabled for now as it will error in many things that are improductive to fix atm
    # - gofumpt # ideally we would like to use it, but has been flaky recently
    # - gomnd # ideally we would like to use it, but might give lots of alerts due to assigned variables (need more investigation on how to use it)
    # - rowserrcheck # currently is not supported due to go 1.18 generics... check later in the year, as it would be good to have this linter
    # - gochecknoglobals # could be useful, but really there are many times globals are fine (example: private isolated to a package), besides our code base has many of those
    # - gochecknoinits # same as `gochecknoinits`

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - lll #expected output for TestCompile are v long
        - funlen
        - dupl # excluding dupl check on tests - many tests follow the same format as they're auto generated by the IDE
