name: Conventions

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  pr_title:
    name: Pull Request title
    runs-on: ubuntu-latest
    steps:
      - name: Validate Pull Request title
        uses: amannn/action-semantic-pull-request@v5.2.0
        with:
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
