name: Semver

on:
  push:
    branches:
      - master

jobs:
  semrel:
    name: Generate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semrel.outputs.version  }}
      changelog: ${{ steps.semrel.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4

      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.PO_GITHUB_TOKEN }}
          force-bump-patch-version: true
